### PR TITLE
Added Roads

### PR DESCRIPTION
**Pull request by oolivero45**
Added roads.

- Added multiple entries to data.js for each type of road
- Added an entry to modules.js for roads in the build menu
- Added a function to game.js called 'game.buildTerrain' - almost identical to 'game.build', but for terrain (e.g. roads)
- Added a function to game.js to crawl roads and find all connected road tiles
- Added a function to game.js to set the correct positioning for each road tile
- Added a function to game.js to combine the two functions above.

### CODE REVIEW

**Comment by oolivero45** [comment]
I may also add dirt paths (as the textures already exist for them), which are cheaper but have a higher movement cost. However, this would mean that the movement cost would have to be a decimal value. Thoughts @dotjersh?

**Comment by joshgrift** [comment]
Hmm... This worries me as I'm not sure if the decimal value will work. Want to fiddle around with it in a test environment first?

**Comment by joshgrift** [comment]
Going to shout this out, how hard would it be to modify this for walls as well? @oolivero45

**Comment by oolivero45** [comment]
You know, I had that exact idea a while ago - not too hard, I don't think. The same code should work with minimal edits? What would walls do? Disallow walking over by other teams?

**Comment by joshgrift** [comment]
Disable all walking. Gates are the only entry point, so that would complicate things.

**Pull request merged**
